### ISSUE TITLE
dictionary returned by 'inc_tmm'  does not include 'lam_vac', 'th_0', 'pol', etc.

### ISSUE THREAD

**Issue by erictai** [sbyrnes321/tmm#10]
A nice feature of 'coh_tmm' is that the 'coh_tmm_data' object includes the input parameters so that you can always double check that you simulated what you wanted to simulate. I don't see a physics reason why this shouldn't be implemented in 'inc_tmm' and seems like would be as easy as adding a few lines at line 739?

**Comment by sbyrnes321** [comment]
You're welcome to make the change in your own copy, or a fork. I consider this software in "maintenance mode"—I'm happy to fix real problems, but otherwise I'd rather leave well enough alone.
