### ISSUE TITLE
Missing dependency from NumPy

### ISSUE THREAD

**Issue by ilario** [sbyrnes321/tmm#14]
Simply importing tmm fails with:

```
import tmm

ModuleNotFoundError                       Traceback (most recent call last)
Cell In[1], line 1
----> 1 import tmm

File ~\.conda\envs\tmm\Lib\site-packages\tmm\__init__.py:36
      2 """
      3 tmm - A transfer-matrix method optics package, for calculating
      4 reflection, transmission, absorption, and other relevant aspects of thin
   (...)
     32 multilayer thin film under reflected light.
     33 """
     34 from __future__ import division, print_function, absolute_import
---> 36 from .tmm_core import *

File ~\.conda\envs\tmm\Lib\site-packages\tmm\tmm_core.py:23
      2 """
      3 For information see the docstring of each function, and also see
      4 manual.pdf (should be included with the distribution, otherwise get it
   (...)
     18 so you can call them with tmm.coh_tmm(...) etc.
     19 """
     21 from __future__ import division, print_function, absolute_import
---> 23 from numpy import cos, inf, zeros, array, exp, conj, nan, isnan, pi, sin, seterr
     24 from numpy.lib.scimath import arcsin
     26 import numpy as np

ModuleNotFoundError: No module named 'numpy'
```

The need for SciPy and NumPy is mentioned in the [manual](https://github.com/sbyrnes321/tmm/blob/master/manual.pdf), section 4, but not included as dependencies.

I would say that only NumPy needs to be added as a dependency as:
SciPy is needed for running some examples, but not strictly needed.
Matplotlib is needed for running all examples, but not strictly needed.
ColorPy is needed only for some functions.

**Comment by sbyrnes321** [comment]
As stated at #15 , I'm very open to adding a more user-friendly error message if numpy is not there, e.g. in tmm_core we could replace

    from numpy import cos, inf, zeros, array, exp, conj, nan, isnan, pi, sin, seterr

with

    try:
        from numpy import cos, inf, zeros, array, exp, conj, nan, isnan, pi, sin, seterr
    except ImportError:
        print('Error: tmm requires numpy. See https://numpy.org/install/')

(I didn't test that.)

I also think the current behavior is not really an "issue" per se. The above-proposed change is more like a "nice-to-have". So I am closing it. But again, if someone tests and submits a pull request similar to what I proposed just above, that's great.
