### ISSUE TITLE
The chapter "Installation for dummies" does not work

### ISSUE THREAD

**Issue by Aramus92** [sbyrnes321/tmm#3]
You forgot to import pyplot in this example. No plot will show up if you do it like this. 

    import tmm
    import tmm.examples
    import matplotlib.pyplot as plt

    tmm.examples.sample1()

that works.

**Comment by sbyrnes321** [comment]
You're saying that running
```
import tmm.examples
tmm.examples.sample1()
```
does not work, correct? If so, are you speculating, or did you actually run those lines and find them not to work? If you found them not to work, can you say more about your Python environment, how you installed tmm, how you ran those lines (did you type them into ipython, or the command line, or Sublime, or what?), and what error message you got if any?

(Those lines work fine on my computer.)

Thanks in advance for your help,
Steve

**Comment by Aramus92** [comment]
I tried running them in my terminal. But obviously the same thing happens when I use spacemacs and run it in there. I use anaconda. 

It just does not import plt from your example file. I have to load it myself by writing `import matplotlib.pyplot as plt` and then show the plot with `plt.show()`. You just have to add those two lines to your manual i think.

Im no python expert, but maybe its just not possible to load other packages via another imported package?

**Comment by sbyrnes321** [comment]
OK, thanks for the report, I fixed it in 4ebbe9dbee140ccabad22c158107681846c9d204. It should work in the next version!

**Comment by azazello4** [comment]
Windows 10
Python 3.8.2

```
import tmm.examples
tmm.examples.sample1()
```
This produces no plots.
Running the _examples.sample1()_ code as a [script](https://pastebin.com/raw/w71M7STf) by itself does work though. Any input?
Tried in a ipython console with no luck either.

**Comment by sbyrnes321** [comment]
Hmmm, can you try:
````
import matplotlib
matplotlib.pyplot.ion()
import tmm.examples
tmm.examples.sample1()
````

**Comment by azazello4** [comment]
`AttributeError: module 'matplotlib' has no attribute 'pyplot'`

**Comment by sbyrnes321** [comment]
Oh sorry, I meant
````
import matplotlib.pyplot
matplotlib.pyplot.ion()
import tmm.examples
tmm.examples.sample1()
````

**Comment by azazello4** [comment]
That worked, thanks!
