### ISSUE TITLE
Angular dependence for incoherent layers

### ISSUE THREAD

**Issue by P-Tillmann** [sbyrnes321/tmm#4]
Hi,

thank you for your great package and all the effort you put into it. Also i really like the comprehensive documentation of the underlying physics.

I think there is a little error in the calculation of the angular dependence of absorption in incoherent layers. From your archive paper (and the implementation) the fraction of light that passes successfully through layer is:
P = exp(-d(layer) * 4 * pi * Im[n*cos(theta)] / lambda(vac))

With theta being the angle between the light rays and normal incident (If i understood that correctly)
This implies that the absorption decreases with theta going from 0->90 degrees. However from geometrical considerations the absorption should increase because the lightpath in the absorbing material increases with theta and should approach infinity for theta->90.

Is there a mistake in my understanding or in the implementation?

**Comment by sbyrnes321** [comment]
Try this: 
```
import numpy as np
import matplotlib.pyplot as plt
import tmm
n0 = 1
θ0_list = np.linspace(0, np.pi/2)
n1 = 2+0.1j
θ1_list = [tmm.snell(n0,n1,θ0) for θ0 in θ0_list]
plt.plot(θ0_list, (n1*np.cos(θ1_list)).imag)
```
You'll see that Im[n cos θ] goes up, not down, as you get further from normal. Agree?

**Comment by P-Tillmann** [comment]
Thanks for the explanation. I agree!
I had a small test script that showed decreasing absorption for very high angles but i didn't consider the reflection that gets considerable large for these high angles even if the real part of n is identical.
Thanks again!
PS: did you know that your code made it into a package called solcore, for simulating solar cells?
