### ISSUE TITLE
The effect of incident angle on absorption/ phase shift

### ISSUE THREAD

**Issue by MinHsuanWu** [sbyrnes321/tmm#8]
Thanks for making this package. I just want to make sure that this package does not consider that different incident angles can cause different travel distances in the material. When the imaginary part of the reflective index is positive (this means absorption), the larger the incident angle is, the larger the absorption/ phase shift it may cause. But this angle dependence was not considered in this package? 
For example, in `coh_tmm()` I see `delta = kz_list * d_list`. Here you use d_list instead of elements of d_list divided by some cosine value of th_list.

**Comment by sbyrnes321** [comment]
I believe the calculation is correct as written for any incident angle. See https://arxiv.org/abs/1603.02720 for derivations. If you find any specific example result that seems to be wrong, please do tell me about it.

**Comment by MinHsuanWu** [comment]
So d_list is just layer thickness, not the distance that light travel in each layer?

**Comment by sbyrnes321** [comment]
Yes, d_list is the list of layer thicknesses.

**Comment by MinHsuanWu** [comment]
In https://arxiv.org/abs/1603.02720 equation(8), when calculating delta, you use the thickness of layer n instead of the distance the light travels in the layer. I thought this is just the case of normal incidence? Or did you do this approximation only because you are considering thin films?

<img src="https://user-images.githubusercontent.com/30039008/95288311-daecf180-081c-11eb-8929-dfeef6597ead.png" width = "70%">

**Comment by sbyrnes321** [comment]
It's not an approximation. The wavevector k is a complex vector (kx, ky, kz), and a plane wave amplitude is proportional to e^(i(kx·x + ky·y + kz·z)). See Eq. (1). The layer interfaces are parallel to the x-y plane. The z-component of the wavevector kz depends on angle of incidence (as well as wavelength and index of refraction). That's Eqs. (2) and (4). Then kz multiplies the layer thickness in the z (normal) direction.
